const USERS = [
  {
    id: 1,
    role: "Admin",
    userName: "marioRed",
    email: "mario@rossi.col",
    password: "Mario.rossi123",
    name: "mario",
    surname: "rossi",
    gender: "Male",
    company: "mario brothers",
  },
  {
    id: 2,
    role: "Admin",
    userName: "luigiGreen",
    email: "luigi@verdi.cos",
    password: "Luigi.verdi123",
    name: "luigi",
    surname: "verdi",
    gender: "Male",
    company: "mario brothers",
  },
  {
    id: 3,
    role: "User",
    userName: "toadWhite",
    email: "toad@white.mush",
    password: "Toad.white123",
    name: "toad",
    surname: "white",
    gender: "Other",
    company: "toad & co",
  },
  {
    id: 4,
    role: "User",
    userName: "peachPink",
    email: "peach@rosi.zuc",
    password: "Peach.rosi123",
    name: "peach",
    surname: "rosi",
    gender: "Female",
    company: "peach srl",
  },
];

const APPOINTMENT_LIST = [
  {
    id: 1,
    userName: "marioRed",
    title: "salvare la principessa",
    date: "2025-04-08",
    time: "17:05",
    check: false,
  },
  {
    id: 2,
    userName: "luigiGreen",
    title: "aiutare mario",
    date: "2025-04-07",
    time: "08:00",
    check: true,
  },
  {
    id: 3,
    userName: "toadWhite",
    title: "guardare i funghi",
    date: "2110-12-01",
    time: "09:35",
    check: false,
  },
];

module.exports = { USERS, APPOINTMENT_LIST };
